import Head from "next/head";
import styles from "../styles/Main.module.css";
import {signOut} from "next-auth/react";
import {Button} from "@mui/material";

export default function MainLayout() {
    return (
        <>
            <Head>
                <title>Discord delayed messages manager</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.App}>
                <div className={styles.container}>
                    <div className={styles.header}>
                        <h1 className={styles.title}>Discord delayed messages manager</h1>
                        <Button variant="contained" className={styles.headerSignOutButton} onClick={() => {
                            signOut()
                        }}>Sign Out</Button>
                    </div>

                    {/*<Input textBefore={"Тест текст"} onClick={sendWebhook}></Input>*/}
                    {/*<Button variant="contained" onClick={() => {}}>text</Button>*/}


                    {/*<p className={styles.love}>Made with ❤️ by <a className={styles.link}*/}
                    {/*                                              href="https://github.com/litolax/"*/}
                    {/*                                              rel="noreferrer">litolax</a></p>*/}

                </div>
            </main>
        </>
    )
}