import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {connectToDatabase} from "./database";
import Input from "./components/input";
import sendWebhook from "./webhooks";

export default function Home(props: any) {

    console.log(props.hello)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.App}>
                <div className={styles.container}>
                    <h1 className={styles.title}>Discord delayed messages manager</h1> 
                    <Input textBefore={"Тест текст"} onClick={sendWebhook}></Input>
                    <p className={styles.love}>Made with ❤️ by <a className={styles.link} href="https://github.com/litolax/"
                                                                  rel="noreferrer">litolax</a></p>
                </div>
            </main>
        </>
    )
}

export async function getServerSideProps() {
    let {db} = await connectToDatabase();

    let result = await db
        .collection('DayTimetables')
        .find({})
        .toArray()

    //console.log(result);

    return {
        props: {
            hello: ""
        },
    };
}
